import { Button, VerticalBox, TextEdit, HorizontalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    in property <string> file_name;
    in property <int> total_cards;
    in property <int> cards_completed;
    
    callback pick_file();
    callback parse_file();

    width: 500px;

    VerticalBox {
        Text {
            text: "Choose a file to parse";
        }

        HorizontalBox {
            TextInput {
                text: root.file_name;
            }
            Button {
                text: "Choose file...";
                clicked => {
                    root.pick_file();
                }
            }
        }

        Button {
            text: "Parse";
            clicked => {
                root.parse_file();
            }
        }

        Text {
            text: "Status:";
        }

        Text {
            text: cards_completed + " / " + total_cards;
        }
    }
}
