import { Button, VerticalBox, TextEdit } from "std-widgets.slint";

export component AppWindow inherits Window {
    in property <string> file_name;
    in property <string> parsed_file;
    callback pick_file();
    callback parse_file();

    width: 300px;

    VerticalBox {
        Text {
            text: "Choose a file";
        }

        Button {
            text: "Select";
            clicked => {
                root.pick_file();
            }
        }

        Text {
            text: root.file_name;
        }

        Button {
            text: "Parse";
            clicked => {
                root.parse_file();
            }
        }

        TextEdit {
            font-size: 14px;
            width: parent.width;
            height: 300px;
            text: parsed_file;
        }
    }
}
